### ISSUE TITLE
pip install fails with package error

### ISSUE THREAD

**Issue by w601sxs** [aws-samples/sagemaker-studio-image-build-cli#23]
```
/opt/conda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting sagemaker-studio-image-build
  Using cached sagemaker_studio_image_build-0.6.0.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6vqr1td2/sagemaker-studio-image-build_802718701392414ca444c646e5991c5c/setup.py", line 33, in <module>
          package_data={"sagemaker_studio_image_build": ["*.yml", "data/**"]},
        File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 466, in __init__
          for k, v in attrs.items()
        File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 885, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 884, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/opt/conda/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by w601sxs** [comment]
On jupyter system terminal this is an infinite loop:

```
 pip install sagemaker-studio-image-build
Collecting sagemaker-studio-image-build
  Using cached sagemaker_studio_image_build-0.6.0.tar.gz (13 kB)
Requirement already satisfied: boto3<2.0,>=1.10.44 in /opt/conda/lib/python3.7/site-packages (from sagemaker-studio-image-build) (1.17.106)
Collecting sagemaker<3.0
  Downloading sagemaker-2.88.1.tar.gz (527 kB)
     |████████████████████████████████| 527 kB 29.7 MB/s 
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.7/site-packages (from boto3<2.0,>=1.10.44->sagemaker-studio-image-build) (0.9.5)
Collecting s3transfer<0.5.0,>=0.4.0
  Downloading s3transfer-0.4.2-py2.py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 966 kB/s 
Collecting botocore<1.21.0,>=1.20.106
  Downloading botocore-1.20.112-py2.py3-none-any.whl (7.7 MB)
     |████████████████████████████████| 7.7 MB 50.3 MB/s 
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/conda/lib/python3.7/site-packages (from botocore<1.21.0,>=1.20.106->boto3<2.0,>=1.10.44->sagemaker-studio-image-build) (1.25.9)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.7/site-packages (from botocore<1.21.0,>=1.20.106->boto3<2.0,>=1.10.44->sagemaker-studio-image-build) (2.8.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.21.0,>=1.20.106->boto3<2.0,>=1.10.44->sagemaker-studio-image-build) (1.14.0)
Collecting attrs==20.3.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 873 kB/s 
Collecting boto3<2.0,>=1.10.44
  Downloading boto3-1.22.1-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 28.9 MB/s 
Collecting google-pasta
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 717 kB/s 
Collecting numpy>=1.9.0
  Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 46.0 MB/s 
Collecting protobuf>=3.1
  Downloading protobuf-3.20.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 36.9 MB/s 
Collecting protobuf3-to-dict>=0.1.5
  Downloading protobuf3-to-dict-0.1.5.tar.gz (3.5 kB)
Collecting smdebug_rulesconfig==1.0.1
  Downloading smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: importlib-metadata>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from sagemaker<3.0->sagemaker-studio-image-build) (1.6.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.7/site-packages (from sagemaker<3.0->sagemaker-studio-image-build) (20.9)
Collecting pandas
  Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     |████████████████████████████████| 11.3 MB 41.1 MB/s 
Collecting pathos
  Downloading pathos-0.2.8-py2.py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 1.7 MB/s 
Collecting boto3<2.0,>=1.10.44
  Downloading boto3-1.22.0-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 29.6 MB/s 
  Downloading boto3-1.21.46-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 40.4 MB/s 
  Downloading boto3-1.21.45-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 62.5 MB/s 
  Downloading boto3-1.21.44-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 78.3 MB/s 
  Downloading boto3-1.21.43-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 59.3 MB/s 
  Downloading boto3-1.21.42-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 54.8 MB/s 
  Downloading boto3-1.21.41-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 58.9 MB/s 
  Downloading boto3-1.21.40-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 58.2 MB/s 
  Downloading boto3-1.21.39-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 57.6 MB/s 
  Downloading boto3-1.21.38-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 27.9 MB/s 
  Downloading boto3-1.21.37-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 60.2 MB/s 
  Downloading boto3-1.21.36-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 43.6 MB/s 
  Downloading boto3-1.21.35-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 27.7 MB/s 
  Downloading boto3-1.21.34-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 57.5 MB/s 
  Downloading boto3-1.21.33-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 25.9 MB/s 
  Downloading boto3-1.21.32-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 61.9 MB/s 
  Downloading boto3-1.21.31-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 60.3 MB/s 
  Downloading boto3-1.21.30-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 59.9 MB/s 
  Downloading boto3-1.21.29-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 52.8 MB/s 
  Downloading boto3-1.21.28-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 53.1 MB/s 
  Downloading boto3-1.21.27-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 59.5 MB/s 
  Downloading boto3-1.21.26-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 49.8 MB/s 
  Downloading boto3-1.21.25-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 32.1 MB/s 
  Downloading boto3-1.21.24-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 42.8 MB/s 
  Downloading boto3-1.21.23-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 51.4 MB/s 
  Downloading boto3-1.21.22-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 11.4 MB/s 
  Downloading boto3-1.21.21-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 45.1 MB/s 
  Downloading boto3-1.21.20-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 59.1 MB/s 
  Downloading boto3-1.21.19-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 57.9 MB/s 
  Downloading boto3-1.21.18-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 51.9 MB/s 
  Downloading boto3-1.21.17-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 59.0 MB/s 
  Downloading boto3-1.21.16-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 57.2 MB/s 
  Downloading boto3-1.21.15-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 61.1 MB/s 
  Downloading boto3-1.21.14-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 53.4 MB/s 
  Downloading boto3-1.21.13-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 55.8 MB/s 
  Downloading boto3-1.21.12-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 29.1 MB/s 
  Downloading boto3-1.21.11-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 28.2 MB/s 
  Downloading boto3-1.21.10-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 58.3 MB/s 
  Downloading boto3-1.21.9-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 50.7 MB/s 
  Downloading boto3-1.21.8-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 54.7 MB/s 
  Downloading boto3-1.21.7-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 41.8 MB/s 
  Downloading boto3-1.21.6-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 40.4 MB/s 
  Downloading boto3-1.21.5-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 61.9 MB/s 
  Downloading boto3-1.21.4-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 61.1 MB/s 
  Downloading boto3-1.21.3-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 56.3 MB/s 
  Downloading boto3-1.21.2-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 63.2 MB/s 
  Downloading boto3-1.21.1-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 52.3 MB/s 
  Downloading boto3-1.21.0-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 61.7 MB/s 
  Downloading boto3-1.20.54-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 57.1 MB/s 
  Downloading boto3-1.20.53-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 61.2 MB/s 
  Downloading boto3-1.20.52-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 55.7 MB/s 
  Downloading boto3-1.20.51-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 68.0 MB/s 
  Downloading boto3-1.20.50-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 47.1 MB/s 
  Downloading boto3-1.20.49-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 45.3 MB/s 
  Downloading boto3-1.20.48-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 61.2 MB/s 
  Downloading boto3-1.20.47-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 60.8 MB/s 
  Downloading boto3-1.20.46-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 61.9 MB/s 
  Downloading boto3-1.20.45-py3-none-any.whl
```


In any case, something is up.

**Comment by dawid-laszuk-sp** [comment]
For the first problem you need to use older version of `setuptools`.

Run this:
```
pip install --upgrade --force-reinstall setuptools~=42.0.0
```
